### ISSUE TITLE
Preservation of Multi-Line Basic Strings in TOML Parsing

### ISSUE THREAD

**Issue by maliknajjar** [squirrelchat/smol-toml#29] opened 2024-10-01 23:08 UTC
Hi,

I've encountered an issue with the preservation of multi-line basic strings while using the smol-toml parser in one of my projects.

When parsing and then converting a multi-line basic string (as defined in the [TOML v1.0.0 specification](https://toml.io/en/v1.0.0#string)), the new line characters (\n) are not properly retained. Instead, the string is converted into a basic single-line string, even though the original content includes new lines.

For example:

when I parse this into a js object
![image](https://github.com/user-attachments/assets/d94a88fd-dd24-4f35-8c54-00ce3acab0c8)

and then I try to strigify that js object into a toml string again it shows like this
![image](https://github.com/user-attachments/assets/f63daec9-cdba-441e-b4db-fa0369fbbbd9)

A possible solution is for the parser to check if a string contains a newline character. If it does, the string should be formatted as a multi-line TOML string.

Let me know if further details are needed!

**Comment by cyyynthia** [comment] 2024-10-02 09:38
Well, semantically speaking the lib *is* properly retaining the newline, both strings are byte equivalent. The problem is that you're hitting one of the limitations of the lib: it is not meant for complete preservation of documents, but rather values. It does not care what the original document looked like and will stringify it to whatever the code is outputting.

FWIW, this issue applies to:
- Single-line vs multi-line strings
- Strings vs literal strings
- Numeric separators
- Indentation
- Datetime separator (T or <space>)
- Inline tables and dotted-keys
- Array of inline tables
- Comments
- Form of floating point numbers
- Probably some more I forgot

The question to have formatting options is tracked by #13. Preservation of comments is tracked by #17. I'm inclined to close this as dupe of #13 specifically

**Comment by 2colours** [comment] 2024-10-02 10:08
Just to restate here as well: the upstream issue that led to this library https://github.com/maliknajjar/guifier/issues/7 seems to be rather that the GUI input field dropped the newline characters outright. However, that doesn't seem to be caused by the library, and it's not stated in the issue either.

**Comment by maliknajjar** [comment] 2024-10-02 11:56
it wouldn't really matter. Even if the text editor interpreted the `\n` as new lines, it would result in:

```
multi_line_string = "Line1
Line2
Line3"
```

which is invalid TOML syntax. it should be three quotes instead of one
like this
```
multi_line_string = """Line1
Line2
Line3"""
```

**Comment by maliknajjar** [comment] 2024-10-02 11:58
so for now. there is no way to produce multi-line strings using the stringify method

**Comment by cyyynthia** [comment] 2024-10-02 13:06
Multi-line strings vs single-line strings is only a stylistic difference. The two examples you've provided in the issue post are byte-equivalent, and is a correct representation of the multiline string. See the [TOML spec for strings](https://toml.io/en/v1.0.0#string), specifically multi-line basic strings.

With regards to correctness, the lib is working as expected.
![image](https://github.com/user-attachments/assets/a61b0c93-3d86-4612-8468-fe79afac0de2)

As I said, using multi-line strings is a stylistic preference which is something tracked under #13. While it is not the prettiest output, newlines are serialized properly.

**Closed as not planned** 2024-10-05 17:53 UTC
Labels: duplicate, enhancement
